### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'is_mount'

### ISSUE THREAD

**Issue by Chuntzu12** [jamesl33/pytranscoder#2]
Was not sure what title to give this, my apologizes if this was not correct. I have tried running pytranscoder against the same bbb_sunflower_1080p_30fps_normal.mp4 to test the transcoder out. I have receieved this same error message on ubuntu 18.04.04 and Windows 10 using linux subsystem. Thank you for any help figuring out how to stop this error and have the transcoder start running. I am excited to get this up and going. Below is the command along with the output run in linux subsystem for windows 10.

`pytranscoder --dry-run -p x264 /mnt/c/Users/Admin/Documents/bbb_sunflower_1080p_30fps_normal.mp4
Exception in thread _default_:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/derek/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 63, in run
    self.go()
  File "/home/derek/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 80, in go
    if is_mounted(job.inpath) and self.config.fls_path():
  File "/home/derek/.local/lib/python3.6/site-packages/pytranscoder/utils.py", line 89, in is_mounted
    if str(part) != str(part.root) and part.is_mount():
AttributeError: 'PosixPath' object has no attribute 'is_mount'`

**Comment by jamesl33** [comment]
Hi @Chuntzu12,
I believe you're using a different tool which happens to have the same name as this one (I had no idea until just now, this tool is pretty limited and isn't published it on PyPi). The stack trace you have linked looks to match the code in [this](https://github.com/mlsmithjr/transcoder) repository. From the looks of it there's an issue with their 'is_mounted' check (which doesn't seem to be supported on Windows 10). I'm more than happy to provide any help I can debugging the issue but you might find more useful help if you raise an issue on the other repository.

**Comment by Chuntzu12** [comment]
Wow! I am so sorry about that. I appreciate the follow up. Have a great day.
